<?php
namespace Snower\LaravelForsun\Client;
/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


interface ForsunIf {
  /**
   * @return int
   */
  public function ping();
  /**
   * @param string $key
   * @param int $second
   * @param int $minute
   * @param int $hour
   * @param int $day
   * @param int $month
   * @param int $week
   * @param string $action
   * @param array $params
   * @return \Snower\LaravelForsun\Client\ForsunPlan
   * @throws \Snower\LaravelForsun\Client\ForsunPlanError
   */
  public function create($key, $second, $minute, $hour, $day, $month, $week, $action, array $params);
  /**
   * @param string $key
   * @param int $second
   * @param int $minute
   * @param int $hour
   * @param int $day
   * @param int $month
   * @param int $week
   * @param int $count
   * @param string $action
   * @param array $params
   * @return \Snower\LaravelForsun\Client\ForsunPlan
   * @throws \Snower\LaravelForsun\Client\ForsunPlanError
   */
  public function createTimeout($key, $second, $minute, $hour, $day, $month, $week, $count, $action, array $params);
  /**
   * @param string $key
   * @return \Snower\LaravelForsun\Client\ForsunPlan
   * @throws \Snower\LaravelForsun\Client\ForsunPlanError
   */
  public function remove($key);
  /**
   * @param string $key
   * @return \Snower\LaravelForsun\Client\ForsunPlan
   * @throws \Snower\LaravelForsun\Client\ForsunPlanError
   */
  public function get($key);
  /**
   * @return \Snower\LaravelForsun\Client\ForsunPlan[]
   */
  public function getCurrent();
  /**
   * @param int $timestamp
   * @return \Snower\LaravelForsun\Client\ForsunPlan[]
   */
  public function getTime($timestamp);
  /**
   * @param string $prefix
   * @return string[]
   */
  public function getKeys($prefix);
  /**
   * @param string $key
   * @param int $ts
   * @param array $params
   */
  public function forsun_call($key, $ts, array $params);
}


